inherit_gem:
  bixby: bixby_default.yml
Rails/Delegate:
  Enabled: false
Rails/Date:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
